"""empty message

Revision ID: 82b2b7ed7832
Revises: 8ccb95f02a03
Create Date: 2018-01-15 04:51:26.649947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82b2b7ed7832'
down_revision = '8ccb95f02a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userclinic')
    op.drop_table('userrole')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userrole',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modify_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modify_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['modify_by'], ['user.id'], name='userrole_modify_by_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='userrole_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userrole_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='userrole_pkey')
    )
    op.create_table('userclinic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userrole_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modify_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name='userclinic_clinic_id_fkey'),
    sa.ForeignKeyConstraint(['userrole_id'], ['user_role.id'], name='userclinic_userrole_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='userclinic_pkey')
    )
    # ### end Alembic commands ###
