"""empty message

Revision ID: 8ccb95f02a03
Revises: d4893ea4c4c8
Create Date: 2018-01-15 04:45:11.254177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ccb95f02a03'
down_revision = 'd4893ea4c4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_clinic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_clinic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userrole_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modify_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name='user_clinic_clinic_id_fkey'),
    sa.ForeignKeyConstraint(['userrole_id'], ['user_role.id'], name='user_clinic_userrole_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_clinic_pkey')
    )
    # ### end Alembic commands ###
