"""empty message

Revision ID: d4893ea4c4c8
Revises: 5f64cda8dcaa
Create Date: 2018-01-11 15:50:23.841777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4893ea4c4c8'
down_revision = '5f64cda8dcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('phone_no', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_no')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
